package util;

public enum PropertyKeys {
    MANUAL, ENTER_COMMAND, ENTER_FIRST_NAME,
    ENTER_LAST_NAME, FOR_FIND, FOR_REMOVE ,
    FIRST_NAME, LAST_NAME, WRONG_COMMAND, EMPLOYEE_ADDED, WRONG_LAST_NAME, EMPLOYEE_REMOVED, EMPLOYEE_LIST_IS_EMPTY;
}
